---
- name: Install packets to master node
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade packets
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Copy file with owner and permission, using symbolic representation
      ansible.builtin.copy:
        src: ./default
        dest: /etc/nginx/sites-available/default
    
    - name: Copy archive with website to web server
      copy:
        src: ./tmsby.tar.gz
        dest: /tmp/tmsby.tar.gz
        
    - name: Unarchive website in /var/www/tms-by
      unarchive:
        src: /tmp/tmsby.tar.gz
        dest: /var/www
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes
               
###
#
#
#
#
